### PR TITLE
Lock glob to specific version.

### PR DESCRIPTION
**Pull request by rwjblue**
Closes https://github.com/broccolijs/broccoli-kitchen-sink-helpers/issues/27.

### CODE REVIEW

**Comment by rwjblue** [comment]
@joliss - Can we get a release for this?

**Comment by joliss** [comment]
Done :)

**Comment by joliss** [comment]
And thanks for fixing. We should really investigate some time, I'm a bit worried that this will break things left and right for us.

**Comment by rwjblue** [comment]
@joliss - node-glob is attempting to match the behavior of bash, which changed in the symlink following case so node-glob "fixed" it.  Unfortunately, we actually want the old behavior (always follow dir symlinks).  There is an issue (https://github.com/isaacs/node-glob/issues/139) to add a `follow: true` option to always follow symlinks, but there doesn't seem to be any movement on implementation there yet.

**Pull request merged**
